name: learn_english
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    # Images
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/cao.png
    - assets/images/direitos.png
    - assets/images/gato.png
    - assets/images/leao.png
    - assets/images/macaco.png
    - assets/images/ovelha.png
    - assets/images/segundo_fundo.jpg
    - assets/images/segundo_fundo.png
    - assets/images/vaca.png
    # Audios
    - assets/audios/1.mp3
    - assets/audios/2.mp3
    - assets/audios/3.mp3
    - assets/audios/4.mp3
    - assets/audios/5.mp3
    - assets/audios/6.mp3
    - assets/audios/cao.mp3
    - assets/audios/gato.mp3
    - assets/audios/leao.mp3
    - assets/audios/macaco.mp3
    - assets/audios/ovelha.mp3
    - assets/audios/vaca.mp3